config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @message = Message.new
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
  @message = Message.new message_params
    respond_to do |format|
      messages = Message.all
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was sent successfully .' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @messages_path, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:message_content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<center>
  <body>

    <div class= "jumbotron jumbotron-fluid", style= "background: darkorange; padding: 10px;width: 700px;" >
    <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>&nbsp; &nbsp
<% else %> 
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link', class: "signup_button"  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link', class: "login_button"  %>
<% end %>
</p>
    <% if notice %>
  <p class="alert alert-success" role= "alert"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger" role= "alert"><%= alert %></p>
<% end %>
    <%= yield %>
  </div>
  </body>
</center>

</html>

<style type="text/css">
  .signup_button {
    color: ghostwhite;
    background: darkorange;
    padding: 5px 20px;
    border: solid;
  }

</style>
<style type="text/css">
.login_button{
    color: ghostwhite;
    border: solid;
    padding: 5px 20px;
    background: darkorange;
}
</style>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :message_content, placeholder: "write message here" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>

  </div>

  <div class="actions">
    <%= form.submit "send message" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>
<div class="jumbotron jumbotron-fluid">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Message</th>
      <th>From</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr >
        <p class="h6"></p>
        <td><%= message.message_content %></td>
        <td><%= message.user.email %></td>
        <td><%= link_to 'Delete message', message, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= form_with(model: @message, local: true) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :message_content, class: "form-control", placeholder: "say something" %><br>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>

  </div>

  <div class="actions">
    <%= form.submit "send message", class: "btn btn-primary" %>
  </div>
<% end %>

<style type="text/css">
  .delete_button{
    color: red;
    padding: 7px;
  }
</style>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message content:</strong>
  <%= @message.message_content %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>